# Azure DevOps Pipeline for OneUp Dashboard
# This pipeline builds and deploys both frontend and backend to Azure

trigger:
  - main
  - master

variables:
  buildConfiguration: "Release"
  azureSubscription: "YourAzureSubscriptionConnectionName" # Update this
  backendAppName: "oneup-dashboard-api"
  frontendAppName: "oneup-dashboard-frontend"
  resourceGroupName: "oneup-dashboard-rg"

stages:
  - stage: Build
    displayName: "Build Applications"
    jobs:
      - job: BuildBackend
        displayName: "Build .NET API"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 8 SDK"
            inputs:
              packageType: "sdk"
              version: "8.x"

          - task: DotNetCoreCLI@2
            displayName: "Restore packages"
            inputs:
              command: "restore"
              projects: "**/OneUpDashboard.Api.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build API"
            inputs:
              command: "build"
              projects: "**/OneUpDashboard.Api.csproj"
              arguments: "--configuration $(buildConfiguration) --no-restore"

          - task: DotNetCoreCLI@2
            displayName: "Publish API"
            inputs:
              command: "publish"
              projects: "**/OneUpDashboard.Api.csproj"
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-build"
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish API Artifacts"
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)/api"
              artifactName: "api"

      - job: BuildFrontend
        displayName: "Build React Frontend"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            displayName: "Use Node.js 18"
            inputs:
              versionSpec: "18.x"

          - script: |
              cd oneup-dashboard-frontend
              npm ci
            displayName: "Install dependencies"

          - script: |
              cd oneup-dashboard-frontend
              npm run build
            displayName: "Build frontend"

          - task: PublishBuildArtifacts@1
            displayName: "Publish Frontend Artifacts"
            inputs:
              pathToPublish: "oneup-dashboard-frontend/dist"
              artifactName: "frontend"

  - stage: Deploy
    displayName: "Deploy to Azure"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployBackend
        displayName: "Deploy API to Azure App Service"
        environment: "production"
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: "Deploy API to Azure App Service"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    appType: "webApp"
                    appName: "$(backendAppName)"
                    package: "$(Pipeline.Workspace)/api"
                    appSettings: |
                      -ASPNETCORE_ENVIRONMENT "Production"
                      -ConnectionStrings__MongoDB "$(MongoDBConnectionString)"
                      -MongoDB__DatabaseName "OneUpDashboard"
                      -AzureAd__TenantId "$(AzureAdTenantId)"
                      -AzureAd__ClientId "$(AzureAdClientId)"
                      -AzureAd__ClientSecret "$(AzureAdClientSecret)"
                      -AzureAd__RedirectUri "$(AzureAdRedirectUri)"
                      -Jwt__Key "$(JwtKey)"
                      -Jwt__Issuer "$(JwtIssuer)"
                      -Jwt__Audience "$(JwtAudience)"

      - deployment: DeployFrontend
        displayName: "Deploy Frontend to Azure Static Web Apps"
        environment: "production"
        pool:
          vmImage: "ubuntu-latest"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureStaticWebApp@0
                  displayName: "Deploy to Azure Static Web Apps"
                  inputs:
                    azureSubscription: "$(azureSubscription)"
                    app_location: "oneup-dashboard-frontend"
                    output_location: "dist"
                    skip_app_build: true
